version: '3.9'
services:
  app:
    build: .
    container_name: algotrading-app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
    restart: always

  redis:
    image: redis:latest
    container_name: algotrading-redis
    ports:
      - '6379:6379'
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: algotrading-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: algotrading
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 5
